server:
  port: 8086
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
#  data:
#    mongodb:
#      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_online
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: <>
