server:
  port: 8000
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/account-service/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/profile-service/users/**
          filters:
            - StripPrefix=2
        - id: cinema-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/cinema-service/**
          filters:
            - StripPrefix=2
        - id: film-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/film-service/**
          filters:
            - StripPrefix=2
        - id: review-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/review-service/**
          filters:
            - StripPrefix=2