server:
  port: 8089
  servlet:
    context-path: /order-service


spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_online
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456789}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

valid-duration: 900
refreshable-duration: 3600
timeDeleteTokenInvalid: 1

cloudinary:
  cloud-name: dbym9b0xi
  api-key: 519992821762232
  api-secret: ZPkLzEwkD0IDiVY2jMZLj6PF0gg
