server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8080
          predicates:
            - Path=/student/**
          filters:
            - AuthTokenFilter

        - id: attendance-score
          uri: http://localhost:8090
          predicates:
            - Path=/score/**
          filters:
            - AuthTokenFilter

        - id: attendance-history
          uri: http://localhost:8070
          predicates:
            - Path=/log/**
          filters:
            - AuthTokenFilter

        - id: attendance
          uri: http://localhost:8000
          predicates:
            - Path=/attendance/**
          filters:
            - AuthTokenFilter

        - id: auth
          uri: http://localhost:8060
          predicates:
            - Path=/auth/**

